---
gitRepo: git@github.com:Kurisu-homework-set/config_tmp.git
gitPullTimeInternal: 30 # second
maps:
  - gitRepoPath: /a.yaml
    local: /tmp/.config/a/config
  - gitRepoPath: /b.yaml
    local: /tmp/.config/b/config